### ISSUE TITLE
Felmeddelande hänger kvar vid inloggning (ibland)

### ISSUE THREAD

**Issue by hg222dt** [latana/1DV450_ms223eq#1]
En (minor) bugg upptäckte jag när jag: 
1. Loggade ut från ett inloggat användarkonto 
2. Försökte logga in genom att posta url:en från inloggningen (då fick jag ett felmeddelande i stil med "please log in to enter this page"), 
3. Sen klicka bakåtpil två gånger och slutligen logga in med användarnamn och lösenord. 
4. På den inloggade sidan hänger felmeddelandet "please log in to enter this page" med.

Vet att detta kanske är ett lite udda användarflöde, men tänker att det beror på något som kan vara värt att kolla upp i koden.

**Comment by latana** [comment]
Okej tack. Det där får jag kolla upp.
