### ISSUE TITLE
Ingen api-nyckel behöv på dina unsafe-metoder

### ISSUE THREAD

**Issue by hg222dt** [latana/1DV450_ms223eq#12]
Användandet av API-nyckel verkar fungera som det ska när man kör din "safe methods", men när man använder dina unsafe methods så går dessa att använda trots att en api-nyckel inte skickas med. Varför är det så? Detta måste ju betyda att det går att posta in data till api:et som oautnticerad klient, vilket låter lite farligt.

**Comment by hg222dt** [comment]
Detta skulle ju antagligen inte detta vara ett problem om ditt API här hade kontrollerat att jwt var korrekt, men vilket den inte gör.

**Comment by latana** [comment]
Det är alldeles riktigt och det funkar nu när jag fixat kontrollen på jwt.

**Comment by 1dv450** [comment]
:+1:
