### ISSUE TITLE
Userkey (jwt) kan vara felaktig och ändå använda unsafe-metoder

### ISSUE THREAD

**Issue by hg222dt** [latana/1DV450_ms223eq#13]
Jag testade att försöka skapa poster med en felaktig userkey (jwt) och det gick hur bra som helst, vilket jag utifrån kraven tänker, inte är önskvärt. Jag såg dessutom att det fungerade likadant på alla unsafe-metoder. Dvs det går då att som vem som helst att ta bort och uppdatera vilka poster som helst i databasen. Då dessa metoder heller inte behöver någon api-nyckel från klienten, kan med andra ord vem som helst (även utan registrerad klient) utföra detta. 

Som jag förstår så fungerar din userkey idag till att registrera användaren på ett specifikt event som denne skapar, vilket ju är en del av dess funktion, och bra att det finns där!

**Comment by latana** [comment]
Problemet är nu fixat och man kan inte köra någon unsafe metod utan en giltig userkey (jwt). Slarvigt testat av mig och bra att du hittade säkerhets luckan. Tackar :)

**Comment by hg222dt** [comment]
Sweet! Detta var det viktigaste! Nice då, ju.
