### ISSUE TITLE
Felmeddelanden bra och tydliga

### ISSUE THREAD

**Issue by hg222dt** [latana/1DV450_ms223eq#15]
Det framgår tydligt vad som gått fel i dina felmedelanden, som både riktar sig till användare och utvecklare.

Däremot känndes det som att jag fick tillbaka ett felmeddelande efter att ha raderat ett event. "Malformed JSON" stod det, vilket kanske var lite väl kryptiskt ;)

**Comment by latana** [comment]
Det var ett konstigt. Jag har inte lyckats få fram det meddelandet men jag ska kolla noggrannare.
