### ISSUE TITLE
Det är möjligt att gå in på utloggad användare genom att trycka pil tillbaka.

### ISSUE THREAD

**Issue by hg222dt** [latana/1DV450_ms223eq#2]
1. Logga ut från inloggad användare eller admin.
2. Tryck pil tillbaka.
3. Du får åter tillgång till inloggningssidan med api-nyckel / nycklar.

**Comment by latana** [comment]
Okej tackar! Det här får jag ta en titt på.

**Comment by 1dv450** [comment]
Vill man komma förbi det får man se till att sätta om headers så att webbläsaren inte cachar samt att stänga av turbolinks för utloggning. Jag i releasen i mitt exempelrepo:
https://github.com/thajo/1dv450_demo/blob/master/app/controllers/application_controller.rb
