### ISSUE TITLE
Ska en användare kunna regenerera en ny nyckel?

### ISSUE THREAD

**Issue by hg222dt** [latana/1DV450_ms223eq#5]
Jag tycker nog det är lite konstigt att en användare själv kan generera en ny nyckel när denna blivit borttagen av administratören. Detta motverkar väl syftat att admin ska ha makten att dra in nycklar, om användaren själv ändå kan skapa en ny sen? Sen är det iof strålande att en användare själv kan regenerera en ny nyckel när denne tagit bort sin egen!

**Comment by latana** [comment]
Den ursprungliga tanken var att användaren inte skulle kunna återskapa en nyckel men för att underlätta för mig själv i framtiden så bestämde jag mig för att skapa en sådan funktion när jag tester andra labbar i kursen. Annars håller jag med dig.

**Comment by 1dv450** [comment]
Det kan ju vara som så att nycklen kommer på villovägar och används av andra än själva nyckelägaren. Admin ser det på statistiken och kör revoke meddelar api-användaren om det lämnar sedan ansvaret att skapa en ny. Dock brukar man kanske i stället köra ett max-antal anrop på en nyckel och att admin använder revoke mer vid abuse och då borde kanske inte användaren kunna göra en ny utan att kontakta API-ägaren.
