### ISSUE TITLE
Inget direkt sätt att ta sig till där man skapar api nycklar.

### ISSUE THREAD

**Issue by ch222kv** [latana/1DV450_ms223eq#7]
När man loggar in med admin@mail.com så finns det inget sätt att skapa api nycklar. Är det tänkt att man ska kunna skapa api nycklar, eller hur fungerar det med admin?
När jag läser koden så är det ganska tydligt att användare ges en api nyckel när de skapar sitt konto, men det finns inga tydliga instruktioner varken på sidan eller någon annanstans att detta är fallet. Och det är förvirrande att administratören, som verkar vara en instans av User inte får en nyckel, men att det kommer upp en `Api key:` när man går in på /users/1.

**Comment by latana** [comment]
Den ursprungliga tanken var att användaren inte skulle kunna återskapa en nyckel men för att underlätta för mig själv i framtiden så bestämde jag mig för att skapa en sådan funktion. Men det där med /users/1 är alla andras api-nycklar. En vanlig användare kan bara komma åt sin egna visnings sida.
