### ISSUE TITLE
Skapa en ny controller för Applikationer

### ISSUE THREAD

**Issue by ch222kv** [latana/1DV450_ms223eq#8]
Med tanke på separation of concerns så bör du bryta ut Key funktioner till en egen controller. Det är inte heller logiskt när man tittar igenom koden att kolla i users_controller för att hitta logiken för hur nycklar skapas, särskilt som users_controller inte hanterar något som har med Users att göra.

**Comment by 1dv450** [comment]
Bra kommentar!
